version: '3'
networks:
  app-tier:
    driver: bridge
services:
  mongodb:
    image: 'mongo:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '27017:27017'
    volumes:
      - /var/lib/mongodb/data
    networks:
      - app-tier
  my-app:
    image: 'upload-and-search:latest'
    ports:
      - '8080:8080'
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
    networks:
      - app-tier
    depends_on:
      - mongodb
volumes:
  mongodb:
    driver: local